{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Fundamental Data Visualization using R.r",
      "private_outputs": true,
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "DLXUKYXpBqKV"
      },
      "source": [
        "### [Visualisasi - Part 1: ggplot](https://academy.dqlab.id/main/livecode/257/468/2329)"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "jfbiRJehBpHa"
      },
      "source": [
        "library(dplyr)\n",
        "library(ggplot2)\n",
        "\n",
        "tabel <- read.csv(\"https://storage.googleapis.com/dqlab-dataset/lo5_m01_mp01.csv\") %>%\n",
        "mutate(Laki.laki = -Laki.laki) %>%\n",
        "arrange(desc(Kelompok.Usia))\n",
        "\n",
        "plt <- ggplot(data = tabel,\n",
        "aes(x = factor(tabel$Kelompok.Usia,\n",
        "levels = tabel$Kelompok.Usia))) +\n",
        "geom_bar(stat = \"identity\",\n",
        "width = 0.8,\n",
        "fill = \"blue\",\n",
        "aes(y = Laki.laki)) +\n",
        "geom_text(aes(x = Kelompok.Usia,\n",
        "y = Laki.laki + 27,\n",
        "label = abs(Laki.laki)),\n",
        "colour = \"white\") +\n",
        "geom_bar(stat = \"identity\",\n",
        "width = 0.8,\n",
        "fill = \"orange\",\n",
        "aes(y = Perempuan)) +\n",
        "geom_text(aes(x = Kelompok.Usia,\n",
        "y = Perempuan - 27,\n",
        "label = Perempuan),\n",
        "colour = \"white\") +\n",
        "ylim(-550, 550) +\n",
        "coord_flip() +\n",
        "annotate(\"text\", x=0.5, y=-20, hjust=1,\n",
        "label=\"Laki-laki\", colour=\"blue\") +\n",
        "annotate(\"text\", x=0.5, y=20, hjust=0,\n",
        "label=\"Perempuan\", colour=\"orange\") +\n",
        "labs(colour = \"\", x = \"\", y = \"\",\n",
        "title = \"Perbandingan Jumlah Karyawan Laki-laki dan Perempuan\\nBerdasarkan Kelompok Usia\") +\n",
        "theme(axis.text = element_text(size = 12, face=\"bold\"),\n",
        "axis.text.x = element_blank(),\n",
        "axis.ticks = element_blank(),\n",
        "plot.title = element_text(hjust = 0, size = 16),\n",
        "panel.background = element_rect(fill = \"white\"),\n",
        "legend.position = \"bottom\")\n",
        "\n",
        "options(repr.plt.width = 10, repr.plt.height = 2)\n",
        "plt"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "opjGuYlASUP1"
      },
      "source": [
        "### [Visualisasi - Part 2: ggplot](https://academy.dqlab.id/main/livecode/257/468/2332)"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Tp-fLT8dSVZr"
      },
      "source": [
        "library(dplyr)\n",
        "library(ggplot2)\n",
        "\n",
        "tabel <- read.csv(\"https://storage.googleapis.com/dqlab-dataset/lo5_m01_mp02.csv\") %>%\n",
        "\tmutate(Bulan = substr(Bulan, 1, 3),\n",
        "\t\t   Karyawan.A = Karyawan.A/1000,\n",
        "\t\t   Karyawan.B = Karyawan.B/1000,\n",
        "\t\t   Karyawan.C = Karyawan.C/1000,\n",
        "\t\t   Karyawan.D = Karyawan.D/1000,\n",
        "\t\t   Karyawan.E = Karyawan.E/1000)\n",
        "\n",
        "plt <- ggplot(data = tabel,\n",
        "\t\taes(x = factor(tabel$Bulan, levels = tabel$Bulan))) +\n",
        "\tgeom_line(aes(y = Karyawan.A, group=1,\n",
        "\t\t\t\t  colour = \"Karyawan A\"),\n",
        "\t\t\t  colour = \"gray\",\n",
        "\t\t\t  size = 1) +\n",
        "\tgeom_line(aes(y = Karyawan.B, group=1),\t\t\t\t \n",
        "\t\t\t  colour = \"gray\",\n",
        "\t\t\t  size = 1.25) +\n",
        "\tgeom_line(aes(y = Karyawan.C, group=1),\t\t\t\t  \n",
        "\t\t\t  colour = \"gray\",\n",
        "\t\t\t  size = 0.75) +\n",
        "\tgeom_line(aes(y = Karyawan.D, group=1),\t\t\t\t \n",
        "\t\t\t  colour = \"gray\",\n",
        "\t\t\t  size = 1.5) +\n",
        "\tgeom_line(aes(y = Karyawan.E, group=1),\t\t\t\t  \n",
        "\t\t\t  colour = \"darkblue\",\n",
        "\t\t\t  size = 2) +\t\n",
        "\tylim(10, 40) +\n",
        "\n",
        "#Produktivitas Tertinggi\n",
        "annotate(\"segment\", x=8.5, xend=9, y=38, yend=max(tabel$Karyawan.E),\n",
        "\t\t colour=\"darkblue\", size=0.5)+\n",
        "annotate(\"text\", x=7.5, 38, size=3, hjust=0, colour=\"darkblue\",\n",
        "\t\t label=paste(\"Produktivitas\\ntertinggi\\n\",\n",
        "\t\t\t\t\t toString(max(tabel$Karyawan.E))))+\n",
        "\t\t\t  \n",
        "#Karyawan A\n",
        "annotate(\"segment\", x=12, xend=12.15, colour=\"grey\", size=0.5,\n",
        "\t\t y=tabel$Karyawan.A[12], yend=tabel$Karyawan.A[12]-1.5)+\t\t \n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.A[12]-1,\n",
        "\t\t hjust=0, colour=\"grey\", label=\"Karyawan A\")+\n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.A[12]-2,\n",
        "\t\t hjust=0, colour=\"grey\", size=3,\n",
        "\t\t label=paste(\"avg:\", toString(mean(tabel$Karyawan.A))))+\n",
        "\t\t\t  \n",
        "#Karyawan B\n",
        "annotate(\"segment\", x=12, xend=12.15, colour=\"grey\", size=0.5,\n",
        "\t\t y=tabel$Karyawan.B[12], yend=tabel$Karyawan.B[12]+1.5)+\t\t \n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.B[12]+2,\n",
        "\t\t hjust=0, colour=\"grey\", label=\"Karyawan B\")+\n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.B[12]+1,\n",
        "\t\t hjust=0, colour=\"grey\", size=3,\n",
        "\t\t label=paste(\"avg:\", toString(mean(tabel$Karyawan.B))))+ \n",
        "\t\t\t  \n",
        "#Karyawan C\n",
        "annotate(\"segment\", x=12, xend=12.15, colour=\"grey\", size=0.5,\n",
        "\t\t y=tabel$Karyawan.C[12], yend=tabel$Karyawan.C[12]+1.5)+\t\t \n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.C[12]+2,\n",
        "\t\t hjust=0, colour=\"grey\", label=\"Karyawan C\")+\n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.C[12]+1,\n",
        "\t\t hjust=0, colour=\"grey\", size=3,\n",
        "\t\t label=paste(\"avg:\", toString(mean(tabel$Karyawan.C))))+\t\n",
        "\t\t\t  \n",
        "#Karyawan D\n",
        "annotate(\"segment\", x=12, xend=12.15, colour=\"grey\", size=0.5,\n",
        "\t\t y=tabel$Karyawan.D[12], yend=tabel$Karyawan.D[12]-1.5)+\t\t \n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.D[12]-1,\n",
        "\t\t hjust=0, colour=\"grey\", label=\"Karyawan D\")+\n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.D[12]-2,\n",
        "\t\t hjust=0, colour=\"grey\", size=3,\n",
        "\t\t label=paste(\"avg:\", toString(mean(tabel$Karyawan.D))))+\t\t\t  \n",
        "\t\t \n",
        "#Karyawan E\n",
        "annotate(\"segment\", x=12, xend=12.15, colour=\"darkblue\", size=0.5,\n",
        "\t\t y=tabel$Karyawan.E[12], yend=tabel$Karyawan.E[12]+0.5)+\t\t \n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.E[12]+1,\n",
        "\t\t hjust=0, colour=\"darkblue\", label=\"Karyawan E\")+\n",
        "annotate(\"text\", x=12.2, y=tabel$Karyawan.E[12],\n",
        "\t\t hjust=0, colour=\"darkblue\", size=3,\n",
        "\t\t label=paste(\"avg:\", toString(mean(tabel$Karyawan.E))))+\n",
        "\t\t\t  \n",
        "labs(x=\"\", y=\"Jumlah produk (ribuan)\\n\",\n",
        "\t title=\"Best Employee 2019\",\n",
        "\t subtitle=\"Lima karyawan dengan produktivitas tertinggi\")+\n",
        "\n",
        "theme(axis.text=element_text(size=10),\n",
        "\t  axis.ticks.x=element_blank(),\n",
        "\t  plot.title=element_text(hjust=0, size=18, face=\"bold\"),\n",
        "\t  panel.background=element_rect(fill=\"white\"))\n",
        "\t\t\t  \n",
        "options(repr.plt.width=10, repr.plt.height=1)\n",
        "plt"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}
